name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
     
    - name: docker login
      env:
       DOCKER_USER : ${{secrets.DOCKER_USER}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: docker build
      run:  docker build . --file Dockerfile --tag alanjino/mydockerfiles
    - name: Docker push
      run : docker push ${{secrets.DOCKER_USER}}/mydockerfiles
    - name: cosign-installer
  # You may pin to the exact commit or the version.
  # uses: sigstore/cosign-installer@536b37ec5d5b543420bdfd9b744c5965bd4d8730
      uses: sigstore/cosign-installer@v2.3.0
      
      
    - name: sign the published docker image
      env:
        COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
      run: cosign sign --key cosign.key alanjino/mydockerfiles
      
